[Settings]
  ID = "b3138fe6-d80a-4ce7-b2bc-06bc90ce383c"

[Build]
  Publish = "public/"
  command = "gatsby build"
  Functions = ""

[Build.environment]
  NODE_ENV = "PRODUCTION"

[context.devel.environment]
  NODE_ENV = "DEVELOPMENT"