[Build]
  Publish = "public"
  command = "npm run build"
  Functions = ""

[Build.environment]
  NODE_ENV = "PRODUCTION"

[context.devel]
  # testwise add the command here --> once merged to master remove and change in build
  command = "npm start build"