[Build]
  Publish = "public/"
  command = "yarn build"
  Functions = ""

[Build.environment]
  NODE_ENV = "PRODUCTION"
  environment = { NODE_VERSION = "10" }

[context.devel.environment]
  NODE_ENV = "DEVELOPMENT"